<a href="https://colab.research.google.com/github/RonakkudalAI/Data-Analysis/blob/main/Day6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = sns.load_dataset("tips")
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [ ]:
print(type(df)) #Type Check

<class 'pandas.core.frame.DataFrame'>

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [ ]:
df.head(10)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
6        8.77  2.00    Male     No  Sun  Dinner     2
7       26.88  3.12    Male     No  Sun  Dinner     4
8       15.04  1.96    Male     No  Sun  Dinner     2
9       14.78  3.23    Male     No  Sun  Dinner     2

In [ ]:
df.tail(10)

     total_bill   tip     sex smoker   day    time  size
234       15.53  3.00    Male    Yes   Sat  Dinner     2
235       10.07  1.25    Male     No   Sat  Dinner     2
236       12.60  1.00    Male    Yes   Sat  Dinner     2
237       32.83  1.17    Male    Yes   Sat  Dinner     2
238       35.83  4.67  Female     No   Sat  Dinner     3
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [ ]:
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [ ]:
df.describe().T

            count       mean       std   min      25%     50%      75%    max
total_bill  244.0  19.785943  8.902412  3.07  13.3475  17.795  24.1275  50.81
tip         244.0   2.998279  1.383638  1.00   2.0000   2.900   3.5625  10.00
size        244.0   2.569672  0.951100  1.00   2.0000   2.000   3.0000   6.00

In [ ]:
#Descriptive Statistical
df.mean(numeric_only=True)

total_bill    19.785943
tip            2.998279
size           2.569672
dtype: float64

In [ ]:
df.median(numeric_only=True)

total_bill    17.795
tip            2.900
size           2.000
dtype: float64

In [ ]:
df.mode()

   total_bill  tip   sex smoker  day    time  size
0       13.42  2.0  Male     No  Sat  Dinner     2

In [ ]:
df["smoker"].mode()

0    No
Name: smoker, dtype: category
Categories (2, object): ['Yes', 'No']

In [ ]:
df["sex"].mode()

0    Male
Name: sex, dtype: category
Categories (2, object): ['Male', 'Female']

In [ ]:
df["smoker"].value_counts()

smoker
No     151
Yes     93
Name: count, dtype: int64

In [ ]:
#Desperssion
df.var(numeric_only=True)

total_bill    79.252939
tip            1.914455
size           0.904591
dtype: float64

In [ ]:
df.std(numeric_only=True)

total_bill    8.902412
tip           1.383638
size          0.951100
dtype: float64

In [ ]:
#Quantile And IQR
Q1 = df.quantile(0.25,numeric_only=True)
Q3 = df.quantile(0.75,numeric_only=True)

IQR = Q3-Q1
print(IQR)

total_bill    10.7800
tip            1.5625
size           1.0000
dtype: float64

In [ ]:
#Outlier Detections
lower_range = Q1-1.5*IQR
upper_range = Q3+1.5*IQR
print(lower_range)

print(upper_range)

total_bill   -2.82250
tip          -0.34375
size          0.50000
dtype: float64
total_bill    40.29750
tip            5.90625
size           4.50000
dtype: float64

In [ ]:
colums = df.select_dtypes(["int64","float64"])
outlier = colums[(colums<lower_range)|(colums>upper_range)]
outlier

     total_bill   tip  size
0           NaN   NaN   NaN
1           NaN   NaN   NaN
2           NaN   NaN   NaN
3           NaN   NaN   NaN
4           NaN   NaN   NaN
..          ...   ...   ...
239         NaN  5.92   NaN
240         NaN   NaN   NaN
241         NaN   NaN   NaN
242         NaN   NaN   NaN
243         NaN   NaN   NaN

[244 rows x 3 columns]

In [ ]:
outlier = [(colums<lower_range)|(colums>upper_range)]
outlier

[     total_bill    tip   size
 0         False  False  False
 1         False  False  False
 2         False  False  False
 3         False  False  False
 4         False  False  False
 ..          ...    ...    ...
 239       False   True  False
 240       False  False  False
 241       False  False  False
 242       False  False  False
 243       False  False  False

 [244 rows x 3 columns]]

In [ ]:
outlier = colums[((colums<lower_range)|(colums>upper_range)).any(axis=1)]
outlier

     total_bill    tip  size
23        39.42   7.58     4
47        32.40   6.00     4
59        48.27   6.73     4
102       44.30   2.50     3
125       29.80   4.20     6
141       34.30   6.70     6
142       41.19   5.00     5
143       27.05   5.00     6
155       29.85   5.14     5
156       48.17   5.00     6
170       50.81  10.00     3
182       45.35   3.50     3
183       23.17   6.50     4
184       40.55   3.00     2
185       20.69   5.00     5
187       30.46   2.00     5
197       43.11   5.00     4
212       48.33   9.00     4
214       28.17   6.50     3
216       28.15   3.00     5
239       29.03   5.92     3

In [ ]:
outlier1 = colums[((colums>=lower_range)|(colums<=upper_range)).any(axis=1)]
outlier1

     total_bill   tip  size
0         16.99  1.01     2
1         10.34  1.66     3
2         21.01  3.50     3
3         23.68  3.31     2
4         24.59  3.61     4
..          ...   ...   ...
239       29.03  5.92     3
240       27.18  2.00     2
241       22.67  2.00     2
242       17.82  1.75     2
243       18.78  3.00     2

[244 rows x 3 columns]

In [ ]:
outlier = colums[~((colums<lower_range)|(colums>upper_range)).any(axis=1)]
outlier.describe()
print(type(outlier))

<class 'pandas.core.frame.DataFrame'>

In [ ]:
outlier is outlier1

False

In [ ]:
# outlier['total_bill'] == outlier1['total_bill']

In [ ]:
outlier.describe()

       total_bill         tip        size
count  223.000000  223.000000  223.000000
mean    18.229596    2.772691    2.408072
std      7.126527    1.062391    0.746962
min      3.070000    1.000000    1.000000
25%     13.015000    2.000000    2.000000
50%     16.970000    2.610000    2.000000
75%     22.175000    3.480000    3.000000
max     40.170000    5.850000    4.000000

In [ ]:
diff_row =outlier[~(outlier==outlier1).all(axis=1)]
print(outlier.compare(outlier1))

ValueError: Can only compare identically-labeled (both index and columns) DataFrame objects

In [ ]:

outlier1 = colums[((colums>=lower_range)&(colums<=upper_range)).all(axis=1)]
print(outlier1)

     total_bill   tip  size
0         16.99  1.01     2
1         10.34  1.66     3
2         21.01  3.50     3
3         23.68  3.31     2
4         24.59  3.61     4
..          ...   ...   ...
238       35.83  4.67     3
240       27.18  2.00     2
241       22.67  2.00     2
242       17.82  1.75     2
243       18.78  3.00     2

[223 rows x 3 columns]

In [ ]:
print(outlier.equals(outlier1))

True

In [ ]:
a = [1,2,3,4]
b= [1,2,3,4]
a is b

False

In [ ]:
a==b

True